create table if not exists public.portfolio_items (
  id bigint generated by default as identity primary key,
  title text not null,
  style text not null,
  image_url text not null,
  description text,
  is_featured boolean not null default true,
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.portfolio_items
add column if not exists is_active boolean not null default true;

create table if not exists public.tattoo_styles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.tattoo_styles (name, display_order)
values
  ('Tradicional', 1),
  ('Old school', 2),
  ('Neo tradicional', 3),
  ('Blackwork', 4),
  ('Fineline', 5),
  ('Lettering', 6),
  ('Color', 7),
  ('Negro y gris', 8)
on conflict (name) do nothing;

insert into public.tattoo_styles (name, display_order)
select distinct style, 100
from public.portfolio_items
where nullif(trim(style), '') is not null
on conflict (name) do nothing;

create table if not exists public.flash_designs (
  id bigint generated by default as identity primary key,
  name text not null,
  price integer not null default 0 check (price >= 0),
  image_url text not null,
  status text not null default 'Disponible' check (status in ('Disponible', 'Reservado', 'Reclamado')),
  style text not null,
  placement text not null,
  size text not null,
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.flash_designs
add column if not exists is_active boolean not null default true;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-images',
  'site-images',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can read site images" on storage.objects;
create policy "Public can read site images"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'site-images');

drop policy if exists "Authenticated can upload site images" on storage.objects;
create policy "Authenticated can upload site images"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'site-images');

drop policy if exists "Authenticated can update site images" on storage.objects;
create policy "Authenticated can update site images"
on storage.objects
for update
to authenticated
using (bucket_id = 'site-images')
with check (bucket_id = 'site-images');

drop policy if exists "Authenticated can delete site images" on storage.objects;
create policy "Authenticated can delete site images"
on storage.objects
for delete
to authenticated
using (bucket_id = 'site-images');

create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  message text not null,
  preferred_placement text,
  budget text,
  status text not null default 'Nueva' check (status in ('Nueva', 'Respondida', 'Archivada')),
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  brand_name text,
  footer_tagline text,
  instagram_url text,
  whatsapp_url text,
  studio_address text,
  studio_hours text,
  artist_name text,
  artist_years text,
  updated_at timestamptz not null default now()
);

insert into public.site_settings (
  id,
  brand_name,
  footer_tagline,
  instagram_url,
  whatsapp_url,
  artist_name,
  updated_at
)
values (
  1,
  'GONZ TATTOO',
  'Tatuajes old school, diseños tradicionales y tinta con carácter.',
  'https://www.instagram.com/gonztattoo',
  'https://wa.link/eodxzz',
  'Gonzalo Regueira',
  now()
)
on conflict (id) do update
set
  brand_name = excluded.brand_name,
  footer_tagline = excluded.footer_tagline,
  instagram_url = excluded.instagram_url,
  whatsapp_url = excluded.whatsapp_url,
  artist_name = excluded.artist_name,
  updated_at = now();

alter table public.portfolio_items enable row level security;
alter table public.tattoo_styles enable row level security;
alter table public.flash_designs enable row level security;
alter table public.contact_requests enable row level security;
alter table public.site_settings enable row level security;

drop policy if exists "Public can read portfolio items" on public.portfolio_items;
create policy "Public can read portfolio items"
on public.portfolio_items
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated can create portfolio items" on public.portfolio_items;
create policy "Authenticated can create portfolio items"
on public.portfolio_items
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated can update portfolio items" on public.portfolio_items;
create policy "Authenticated can update portfolio items"
on public.portfolio_items
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete portfolio items" on public.portfolio_items;
create policy "Authenticated can delete portfolio items"
on public.portfolio_items
for delete
to authenticated
using (true);

drop policy if exists "Public can read tattoo styles" on public.tattoo_styles;
create policy "Public can read tattoo styles"
on public.tattoo_styles
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated can create tattoo styles" on public.tattoo_styles;
create policy "Authenticated can create tattoo styles"
on public.tattoo_styles
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated can update tattoo styles" on public.tattoo_styles;
create policy "Authenticated can update tattoo styles"
on public.tattoo_styles
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete tattoo styles" on public.tattoo_styles;
create policy "Authenticated can delete tattoo styles"
on public.tattoo_styles
for delete
to authenticated
using (true);

drop policy if exists "Public can read flash designs" on public.flash_designs;
create policy "Public can read flash designs"
on public.flash_designs
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated can create flash designs" on public.flash_designs;
create policy "Authenticated can create flash designs"
on public.flash_designs
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated can update flash designs" on public.flash_designs;
create policy "Authenticated can update flash designs"
on public.flash_designs
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete flash designs" on public.flash_designs;
create policy "Authenticated can delete flash designs"
on public.flash_designs
for delete
to authenticated
using (true);

drop policy if exists "Public can create contact requests" on public.contact_requests;
create policy "Public can create contact requests"
on public.contact_requests
for insert
to anon, authenticated
with check (true);

drop policy if exists "Authenticated can read contact requests" on public.contact_requests;
create policy "Authenticated can read contact requests"
on public.contact_requests
for select
to authenticated
using (true);

drop policy if exists "Authenticated can update contact requests" on public.contact_requests;
create policy "Authenticated can update contact requests"
on public.contact_requests
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete contact requests" on public.contact_requests;
create policy "Authenticated can delete contact requests"
on public.contact_requests
for delete
to authenticated
using (true);

drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings"
on public.site_settings
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated can update site settings" on public.site_settings;
create policy "Authenticated can update site settings"
on public.site_settings
for update
to authenticated
using (true)
with check (id = 1);

drop policy if exists "Authenticated can insert site settings" on public.site_settings;
create policy "Authenticated can insert site settings"
on public.site_settings
for insert
to authenticated
with check (id = 1);
