create table if not exists public.tattoo_styles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.tattoo_styles (name, display_order)
values
  ('Tradicional', 1),
  ('Old school', 2),
  ('Neo tradicional', 3),
  ('Blackwork', 4),
  ('Fineline', 5),
  ('Lettering', 6),
  ('Color', 7),
  ('Negro y gris', 8)
on conflict (name) do nothing;

insert into public.tattoo_styles (name, display_order)
select distinct style, 100
from public.portfolio_items
where nullif(trim(style), '') is not null
on conflict (name) do nothing;

alter table public.tattoo_styles enable row level security;

drop policy if exists "Public can read tattoo styles" on public.tattoo_styles;
create policy "Public can read tattoo styles"
on public.tattoo_styles
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated can create tattoo styles" on public.tattoo_styles;
create policy "Authenticated can create tattoo styles"
on public.tattoo_styles
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated can update tattoo styles" on public.tattoo_styles;
create policy "Authenticated can update tattoo styles"
on public.tattoo_styles
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete tattoo styles" on public.tattoo_styles;
create policy "Authenticated can delete tattoo styles"
on public.tattoo_styles
for delete
to authenticated
using (true);
