-- Las tablas portfolio_items y flash_designs NO se tocan.
-- Quedan como backup implícito hasta que se confirme que artworks funciona en producción.
-- Renombrarlas manualmente en Supabase una vez validado el deploy.

-- Tabla unificada de obras
CREATE TABLE public.artworks (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('tattoo', 'flash', 'sculpture', 'painting')),
  title text not null,
  image_url text not null,
  tags text[] not null default '{}'::text[],
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),

  -- solo tatuajes
  description text,
  style text,
  published_date date,
  is_featured boolean default false,

  -- solo vendibles (flash, escultura, cuadro)
  price integer check (price >= 0),
  status text check (status in ('Disponible', 'Reservado', 'Reclamado')),
  dimensions text,
  material text
);

-- Migrar portfolio_items → artworks (type='tattoo')
INSERT INTO public.artworks (
  type, title, image_url, tags, is_active, display_order, created_at,
  description, style, published_date, is_featured
)
SELECT
  'tattoo', title, image_url, tags, is_active, display_order, created_at,
  description, style, published_date, is_featured
FROM public.portfolio_items;

-- Migrar flash_designs → artworks (type='flash')
-- name → title, size → dimensions
INSERT INTO public.artworks (
  type, title, image_url, tags, is_active, display_order, created_at,
  price, status, style, dimensions
)
SELECT
  'flash', name, image_url, tags, is_active, display_order, created_at,
  price, status, style, size
FROM public.flash_designs;

-- RPC para desplazar display_order al crear una nueva obra
CREATE OR REPLACE FUNCTION shift_artworks_display_order(artwork_type text)
RETURNS void AS $$
  UPDATE public.artworks
  SET display_order = display_order + 1
  WHERE type = artwork_type;
$$ LANGUAGE sql;

-- RLS
ALTER TABLE public.artworks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read artworks" ON public.artworks;
CREATE POLICY "Public can read artworks"
ON public.artworks FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated can create artworks" ON public.artworks;
CREATE POLICY "Authenticated can create artworks"
ON public.artworks FOR INSERT
TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated can update artworks" ON public.artworks;
CREATE POLICY "Authenticated can update artworks"
ON public.artworks FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated can delete artworks" ON public.artworks;
CREATE POLICY "Authenticated can delete artworks"
ON public.artworks FOR DELETE
TO authenticated
USING (true);
