create table if not exists public.site_sections (
  id bigint generated by default as identity primary key,
  page_key text not null,
  section_key text not null,
  type text not null,
  enabled boolean not null default true,
  display_order integer not null default 0,
  content jsonb not null default '{}'::jsonb,
  layout jsonb not null default '{}'::jsonb,
  style jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (page_key, section_key)
);

create index if not exists site_sections_page_order_idx
on public.site_sections (page_key, display_order);

alter table public.site_sections enable row level security;

drop policy if exists "Public can read site sections" on public.site_sections;
create policy "Public can read site sections"
on public.site_sections
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated can create site sections" on public.site_sections;
create policy "Authenticated can create site sections"
on public.site_sections
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated can update site sections" on public.site_sections;
create policy "Authenticated can update site sections"
on public.site_sections
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete site sections" on public.site_sections;
create policy "Authenticated can delete site sections"
on public.site_sections
for delete
to authenticated
using (true);

insert into public.site_sections (
  page_key,
  section_key,
  type,
  enabled,
  display_order,
  content,
  layout,
  style,
  updated_at
)
values
  (
    'home',
    'home-hero',
    'hero',
    true,
    10,
    '{
      "eyebrow": "",
      "brandPrimary": "",
      "brandAccent": "",
      "description": "",
      "primaryButtonLabel": "",
      "primaryButtonHref": "",
      "secondaryButtonLabel": "",
      "secondaryButtonHref": ""
    }'::jsonb,
    '{"imagePositionMode": "rotating-mobile"}'::jsonb,
    '{"backgroundImage": "", "overlay": "dark"}'::jsonb,
    now()
  ),
  (
    'home',
    'home-featured-portfolio',
    'featuredPortfolio',
    true,
    20,
    '{
      "eyebrow": "",
      "title": "",
      "highlightedTitle": "",
      "buttonLabel": "",
      "buttonHref": "",
      "dateFrom": "",
      "dateTo": "",
      "featuredOnly": true,
      "filterStyle": "",
      "filterTags": "",
      "limit": 4
    }'::jsonb,
    '{"variant": "carousel"}'::jsonb,
    '{"background": "card"}'::jsonb,
    now()
  ),
  (
    'home',
    'home-flash-preview',
    'flashPreview',
    true,
    30,
    '{
      "eyebrow": "",
      "highlightedTitle": "",
      "description": "",
      "buttonLabel": "",
      "buttonHref": "",
      "filterStyle": "",
      "filterTags": "",
      "limit": 6
    }'::jsonb,
    '{"columnsDesktop": 3, "columnsMobile": 2}'::jsonb,
    '{"background": "default", "frame": "paper"}'::jsonb,
    now()
  ),
  (
    'home',
    'home-about',
    'about',
    true,
    40,
    '{
      "title": "",
      "paragraphs": [],
      "quote": "",
      "stats": [
        { "value": "", "label": "", "tone": "primary" },
        { "value": "", "label": "", "tone": "secondary" },
        { "value": "", "label": "", "tone": "accent" }
      ]
    }'::jsonb,
    '{"imageSide": "left"}'::jsonb,
    '{"background": "card", "image": ""}'::jsonb,
    now()
  ),
  (
    'home',
    'home-contact-cta',
    'contactCta',
    true,
    50,
    '{
      "eyebrow": "",
      "title": "",
      "highlightedTitle": "",
      "description": "",
      "whatsappLabel": "",
      "instagramLabel": "",
      "hoursLabel": ""
    }'::jsonb,
    '{"alignment": "center"}'::jsonb,
    '{"background": "default", "divider": "glow"}'::jsonb,
    now()
  )
on conflict (page_key, section_key) do nothing;
